language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn add --dev eslint
  - yarn add --dev eslint-config-standard
  - yarn add --dev eslint-plugin-node eslint-plugin-react
  - yarn add @fullcalendar/react
  - yarn add @fullcalendar/daygrid
  - yarn add @fullcalendar/timegrid
  - yarn add @fullcalendar/interaction
  - npm run lint
  - npm run build
