language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn add @fullcalendar/react
  - yarn add @fullcalendar/daygrid
  - npm run build
